language: python
python:
    - "2.7"
    - "3.4"
    - "3.6"

install:
    - pip install nose
    - pip install nose2

script:
    - git clone -v https://github.com/ARM-software/devlib.git /tmp/devlib && cd /tmp/devlib && git checkout $DEVLIB_REF && python setup.py install
    - git clone -v https://github.com/ARM-software/workload-automation.git -b next /tmp/wa && cd /tmp/wa && git checkout $WA_REF && python setup.py install
    - nose2 tests

