language: python
python:
    - "2.7"
    - "3.4"
    - "3.6"

env:
    - DEVLIB_REF=c4ababcd50aaec02de924817a1408fe72d5b05fb

install:
    - pip install nose
    - pip install nose2

script:
    - git clone -v https://github.com/ARM-software/devlib.git /tmp/devlib && cd /tmp/devlib && git checkout $DEVLIB_REF && python setup.py install
    - pip install $TRAVIS_BUILD_DIR
    - nose2 -s $TRAVIS_BUILD_fDIR/tests

