apply plugin: 'com.android.application'

def packageName = "com.arm.wa.uiauto.vellamo"

android {
    namespace "${packageName}"
    compileSdkVersion 31
    buildToolsVersion "28.0.3"
    defaultConfig {
        applicationId "${packageName}"
        minSdkVersion 19
        targetSdkVersion 31
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        applicationVariants.all { variant ->
            variant.outputs.each { output ->
                output.outputFileName = "${packageName}.apk"
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.test:runner:1.6.1'
    implementation 'androidx.test:runner:1.6.1'
    implementation 'androidx.test.uiautomator:uiautomator-v18:2.2.0-alpha1'
    implementation(name: 'uiauto', ext:'aar')
}

repositories {
    flatDir {
        dirs 'libs'
    }
}
