apply plugin: 'com.android.application'

def packageName = "com.arm.wa.uiauto.${name}"

android {
    namespace "${packageName}"
    compileSdkVersion 31
    buildToolsVersion '28.0.3'
    defaultConfig {
        applicationId "${package_name}"
        minSdkVersion 19
        targetSdkVersion 31
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        applicationVariants.all { variant ->
            variant.outputs.each { output ->
                output.outputFileName = "${package_name}.apk"
            }
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.test:runner:1.6.1'
    implementation 'androidx.test:rules:1.6.1'
    implementation 'androidx.test.uiautomator:uiautomator-v18:2.2.0-alpha1'
    compile(name: 'uiauto', ext: 'aar')
}

repositories {
    flatDir {
        dirs 'libs'
    }
}
